/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DeepSeekTextOptimizerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/deepseek-api.ts
var import_obsidian = require("obsidian");
var DeepSeekAPI = class {
  constructor(apiKey, model = "deepseek-chat") {
    this.baseUrl = "https://api.deepseek.com/v1/chat/completions";
    this.apiKey = apiKey;
    this.model = model;
  }
  async chat(messages) {
    var _a;
    if (!this.apiKey) {
      throw new Error("DeepSeek API Key \u672A\u8BBE\u7F6E");
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: this.baseUrl,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${this.apiKey}`
        },
        body: JSON.stringify({
          model: this.model,
          messages,
          temperature: 0.7,
          max_tokens: 2e3
        }),
        throw: false
        // 不自动抛出错误，让我们手动处理
      });
      if (response.status >= 400) {
        const errorData = response.json;
        const errorMessage = ((_a = errorData == null ? void 0 : errorData.error) == null ? void 0 : _a.message) || (errorData == null ? void 0 : errorData.message) || `HTTP ${response.status}`;
        throw new Error(`API \u9519\u8BEF (${response.status}): ${errorMessage}`);
      }
      const data = response.json;
      if (data.choices && data.choices.length > 0) {
        return data.choices[0].message.content;
      } else {
        throw new Error("API \u54CD\u5E94\u683C\u5F0F\u9519\u8BEF\uFF1A\u672A\u627E\u5230 choices \u6570\u636E");
      }
    } catch (error) {
      if (error instanceof Error) {
        if (error.message.includes("API \u9519\u8BEF") || error.message.includes("\u54CD\u5E94\u683C\u5F0F\u9519\u8BEF")) {
          throw error;
        }
        throw new Error(`DeepSeek API \u8C03\u7528\u5931\u8D25: ${error.message}`);
      }
      throw new Error("DeepSeek API \u8C03\u7528\u5931\u8D25: \u672A\u77E5\u9519\u8BEF");
    }
  }
  async optimizeText(text) {
    const messages = [
      {
        role: "system",
        content: "\u4F60\u662F\u4E00\u4E2A\u4E13\u4E1A\u7684\u6587\u672C\u4F18\u5316\u52A9\u624B\u3002\u8BF7\u4F18\u5316\u7528\u6237\u63D0\u4F9B\u7684\u6587\u672C\uFF0C\u4F7F\u5176\u8868\u8FBE\u66F4\u52A0\u6D41\u7545\u3001\u6E05\u6670\u3001\u6613\u8BFB\uFF0C\u540C\u65F6\u4FDD\u6301\u539F\u610F\u4E0D\u53D8\u3002\u76F4\u63A5\u8FD4\u56DE\u4F18\u5316\u540E\u7684\u6587\u672C\uFF0C\u4E0D\u8981\u6DFB\u52A0\u4EFB\u4F55\u89E3\u91CA\u6216\u8BF4\u660E\u3002"
      },
      {
        role: "user",
        content: `\u8BF7\u4F18\u5316\u4EE5\u4E0B\u6587\u672C\uFF1A

${text}`
      }
    ];
    return await this.chat(messages);
  }
  async generateInsights(text) {
    const messages = [
      {
        role: "system",
        content: "\u4F60\u662F\u4E00\u4E2A\u601D\u7EF4\u542F\u53D1\u52A9\u624B\u3002\u57FA\u4E8E\u7528\u6237\u63D0\u4F9B\u7684\u6587\u672C\u5185\u5BB9\uFF0C\u63D0\u4F9B\u76F8\u5173\u7684\u601D\u8003\u542F\u53D1\u3001\u5EF6\u4F38\u5EFA\u8BAE\u548C\u62D3\u5C55\u65B9\u5411\u3002\u7528\u6E05\u6670\u7684\u7ED3\u6784\u7EC4\u7EC7\u4F60\u7684\u56DE\u7B54\uFF0C\u53EF\u4EE5\u4F7F\u7528\u5217\u8868\u6216\u5206\u6BB5\u3002"
      },
      {
        role: "user",
        content: `\u8BF7\u4E3A\u4EE5\u4E0B\u6587\u672C\u63D0\u4F9B\u601D\u7EF4\u542F\u53D1\u548C\u5EF6\u4F38\u5EFA\u8BAE\uFF1A

${text}`
      }
    ];
    return await this.chat(messages);
  }
  async provideOpinion(text) {
    const messages = [
      {
        role: "system",
        content: "\u4F60\u662F\u4E00\u4E2A\u89C2\u70B9\u54A8\u8BE2\u52A9\u624B\u3002\u9488\u5BF9\u7528\u6237\u63D0\u4F9B\u7684\u6587\u672C\u5185\u5BB9\uFF0C\u4ECE\u591A\u4E2A\u89D2\u5EA6\u63D0\u4F9B\u89C2\u70B9\u3001\u5206\u6790\u548C\u5EFA\u8BAE\u3002\u53EF\u4EE5\u5305\u62EC\uFF1A\u5BF9\u60F3\u6CD5\u7684\u8BC4\u4EF7\u3001\u4E0D\u540C\u89D2\u5EA6\u7684\u770B\u6CD5\u3001\u6F5C\u5728\u7684\u95EE\u9898\u6216\u6539\u8FDB\u65B9\u5411\u7B49\u3002\u7528\u6E05\u6670\u7684\u7ED3\u6784\u7EC4\u7EC7\u4F60\u7684\u56DE\u7B54\u3002"
      },
      {
        role: "user",
        content: `\u8BF7\u9488\u5BF9\u4EE5\u4E0B\u5185\u5BB9\u63D0\u4F9B\u89C2\u70B9\u3001\u5206\u6790\u548C\u5EFA\u8BAE\uFF1A

${text}`
      }
    ];
    return await this.chat(messages);
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  model: "deepseek-chat",
  autoReplace: false
};
var DeepSeekSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "DeepSeek \u6587\u672C\u4F18\u5316\u5668\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("API Key").setDesc("\u8BF7\u8F93\u5165\u4F60\u7684 DeepSeek API Key").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u9009\u62E9\u4F7F\u7528\u7684 DeepSeek \u6A21\u578B").addDropdown((dropdown) => dropdown.addOption("deepseek-chat", "deepseek-chat").addOption("deepseek-coder", "deepseek-coder").setValue(this.plugin.settings.model).onChange(async (value) => {
      this.plugin.settings.model = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u81EA\u52A8\u66FF\u6362\u539F\u6587").setDesc("\u4F18\u5316\u540E\u662F\u5426\u81EA\u52A8\u66FF\u6362\u9009\u4E2D\u7684\u6587\u672C\uFF08\u5173\u95ED\u5219\u521B\u5EFA\u65B0\u7248\u672C\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoReplace).onChange(async (value) => {
      this.plugin.settings.autoReplace = value;
      await this.plugin.saveSettings();
    }));
  }
};

// main.ts
var DeepSeekTextOptimizerPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.deepSeekAPI = null;
    this.statusBarItem = null;
  }
  async onload() {
    await this.loadSettings();
    this.addStyles();
    if (this.settings.apiKey) {
      this.deepSeekAPI = new DeepSeekAPI(this.settings.apiKey, this.settings.model);
    }
    this.addStatusBar();
    this.addRibbonIcon("sparkles", "DeepSeek \u6587\u672C\u4F18\u5316\u5668", async (evt) => {
      await this.showRibbonMenu(evt);
    });
    this.addCommand({
      id: "optimize-text",
      name: "\u4F18\u5316\u6587\u672C",
      editorCallback: async (editor, view) => {
        await this.optimizeText(editor);
      }
    });
    this.addCommand({
      id: "generate-insights",
      name: "\u601D\u7EF4\u542F\u53D1",
      editorCallback: async (editor, view) => {
        await this.generateInsights(editor);
      }
    });
    this.addCommand({
      id: "provide-opinion",
      name: "AI \u89C2\u70B9\u54A8\u8BE2",
      editorCallback: async (editor, view) => {
        await this.provideOpinion(editor);
      }
    });
    this.addCommand({
      id: "optimize-and-insights",
      name: "\u4F18\u5316\u6587\u672C + \u601D\u7EF4\u542F\u53D1",
      editorCallback: async (editor, view) => {
        await this.optimizeAndInsights(editor);
      }
    });
    this.addCommand({
      id: "optimize-and-opinion",
      name: "\u4F18\u5316\u6587\u672C + AI \u89C2\u70B9\u54A8\u8BE2",
      editorCallback: async (editor, view) => {
        await this.optimizeAndOpinion(editor);
      }
    });
    this.addCommand({
      id: "all-features",
      name: "\u5168\u90E8\u529F\u80FD\uFF08\u4F18\u5316 + \u601D\u7EF4\u542F\u53D1 + \u89C2\u70B9\u54A8\u8BE2\uFF09",
      editorCallback: async (editor, view) => {
        await this.allFeatures(editor);
      }
    });
    this.addSettingTab(new DeepSeekSettingTab(this.app, this));
  }
  onunload() {
    this.deepSeekAPI = null;
    if (this.statusBarItem) {
      this.statusBarItem.remove();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.updateStatusBar();
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.settings.apiKey) {
      this.deepSeekAPI = new DeepSeekAPI(this.settings.apiKey, this.settings.model);
    } else {
      this.deepSeekAPI = null;
    }
    this.updateStatusBar();
  }
  addStyles() {
  }
  addStatusBar() {
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("plugin-deepseek-text-optimizer");
    this.updateStatusBar();
  }
  updateStatusBar() {
    if (!this.statusBarItem)
      return;
    if (this.settings.apiKey && this.deepSeekAPI) {
      this.statusBarItem.setText("\u2728 DeepSeek \u5DF2\u5C31\u7EEA");
      this.statusBarItem.setAttr("aria-label", "DeepSeek API \u5DF2\u914D\u7F6E\uFF0C\u70B9\u51FB\u67E5\u770B\u83DC\u5355");
      this.statusBarItem.onclick = null;
    } else {
      this.statusBarItem.setText("\u26A0\uFE0F DeepSeek \u672A\u914D\u7F6E");
      this.statusBarItem.setAttr("aria-label", "\u70B9\u51FB\u6253\u5F00\u8BBE\u7F6E\u914D\u7F6E DeepSeek API Key");
      this.statusBarItem.onclick = () => {
        this.app.setting.open();
        this.app.setting.openTabById("deepseek-text-optimizer");
      };
    }
  }
  setStatusBarLoading(text) {
    if (!this.statusBarItem)
      return;
    this.statusBarItem.setText(`\u23F3 ${text}`);
    this.statusBarItem.addClass("is-loading");
  }
  clearStatusBarLoading() {
    if (!this.statusBarItem)
      return;
    this.statusBarItem.removeClass("is-loading");
    this.updateStatusBar();
  }
  async showRibbonMenu(evt) {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!activeView) {
      new import_obsidian3.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
      return;
    }
    const menu = new import_obsidian3.Menu();
    menu.addItem((item) => {
      item.setTitle("\u2728 \u4F18\u5316\u6587\u672C");
      item.setIcon("sparkles");
      item.onClick(async () => {
        await this.optimizeText(activeView.editor);
      });
    });
    menu.addItem((item) => {
      item.setTitle("\u{1F4A1} \u601D\u7EF4\u542F\u53D1");
      item.setIcon("lightbulb");
      item.onClick(async () => {
        await this.generateInsights(activeView.editor);
      });
    });
    menu.addItem((item) => {
      item.setTitle("\u{1F4AC} AI \u89C2\u70B9\u54A8\u8BE2");
      item.setIcon("message-square");
      item.onClick(async () => {
        await this.provideOpinion(activeView.editor);
      });
    });
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("\u2728\u{1F4A1} \u4F18\u5316 + \u601D\u7EF4\u542F\u53D1");
      item.setIcon("sparkles");
      item.onClick(async () => {
        await this.optimizeAndInsights(activeView.editor);
      });
    });
    menu.addItem((item) => {
      item.setTitle("\u2728\u{1F4AC} \u4F18\u5316 + \u89C2\u70B9\u54A8\u8BE2");
      item.setIcon("sparkles");
      item.onClick(async () => {
        await this.optimizeAndOpinion(activeView.editor);
      });
    });
    menu.addItem((item) => {
      item.setTitle("\u{1F680} \u5168\u90E8\u529F\u80FD");
      item.setIcon("rocket");
      item.onClick(async () => {
        await this.allFeatures(activeView.editor);
      });
    });
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("\u2699\uFE0F \u6253\u5F00\u8BBE\u7F6E");
      item.setIcon("settings");
      item.onClick(() => {
        this.app.setting.open();
        this.app.setting.openTabById("deepseek-text-optimizer");
      });
    });
    menu.showAtPosition({ x: evt.clientX, y: evt.clientY });
  }
  getActiveEditor() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    return activeView ? activeView.editor : null;
  }
  getSelectedText(editor) {
    const selection = editor.getSelection();
    if (selection) {
      return selection;
    }
    return editor.getValue();
  }
  async checkAPI() {
    if (!this.deepSeekAPI) {
      new import_obsidian3.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E DeepSeek API Key");
      setTimeout(() => {
        this.app.setting.open();
        this.app.setting.openTabById("deepseek-text-optimizer");
      }, 500);
      return false;
    }
    return true;
  }
  async optimizeText(editor) {
    if (!await this.checkAPI())
      return;
    const text = this.getSelectedText(editor);
    if (!text.trim()) {
      new import_obsidian3.Notice("\u8BF7\u5148\u9009\u4E2D\u8981\u4F18\u5316\u7684\u6587\u672C\uFF0C\u6216\u786E\u4FDD\u6587\u6863\u4E2D\u6709\u5185\u5BB9");
      return;
    }
    new import_obsidian3.Notice("\u6B63\u5728\u4F18\u5316\u6587\u672C...");
    this.setStatusBarLoading("\u4F18\u5316\u4E2D...");
    try {
      const optimized = await this.deepSeekAPI.optimizeText(text);
      this.clearStatusBarLoading();
      if (this.settings.autoReplace) {
        const selection = editor.getSelection();
        if (selection) {
          editor.replaceSelection(optimized);
        } else {
          editor.setValue(optimized);
        }
        new import_obsidian3.Notice("\u2705 \u6587\u672C\u5DF2\u4F18\u5316\u5E76\u66FF\u6362");
      } else {
        const endPos = editor.getCursor("to");
        editor.setCursor(endPos.line + 1, 0);
        editor.replaceSelection(`

## \u4F18\u5316\u540E\u7684\u6587\u672C

${optimized}

---
`);
        new import_obsidian3.Notice("\u2705 \u4F18\u5316\u540E\u7684\u6587\u672C\u5DF2\u6DFB\u52A0\u5230\u6587\u6863\u672B\u5C3E");
      }
    } catch (error) {
      this.clearStatusBarLoading();
      new import_obsidian3.Notice(`\u274C \u4F18\u5316\u5931\u8D25: ${error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"}`);
      console.error("DeepSeek \u4F18\u5316\u9519\u8BEF:", error);
    }
  }
  async generateInsights(editor) {
    if (!await this.checkAPI())
      return;
    const text = this.getSelectedText(editor);
    if (!text.trim()) {
      new import_obsidian3.Notice("\u8BF7\u5148\u9009\u4E2D\u8981\u5206\u6790\u7684\u6587\u672C\uFF0C\u6216\u786E\u4FDD\u6587\u6863\u4E2D\u6709\u5185\u5BB9");
      return;
    }
    new import_obsidian3.Notice("\u6B63\u5728\u751F\u6210\u601D\u7EF4\u542F\u53D1...");
    this.setStatusBarLoading("\u751F\u6210\u4E2D...");
    try {
      const insights = await this.deepSeekAPI.generateInsights(text);
      this.clearStatusBarLoading();
      const endPos = editor.getCursor("to");
      editor.setCursor(endPos.line + 1, 0);
      editor.replaceSelection(`

## \u601D\u7EF4\u542F\u53D1

${insights}

---
`);
      new import_obsidian3.Notice("\u2705 \u601D\u7EF4\u542F\u53D1\u5DF2\u6DFB\u52A0\u5230\u6587\u6863");
    } catch (error) {
      this.clearStatusBarLoading();
      new import_obsidian3.Notice(`\u274C \u751F\u6210\u5931\u8D25: ${error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"}`);
      console.error("DeepSeek \u601D\u7EF4\u542F\u53D1\u9519\u8BEF:", error);
    }
  }
  async provideOpinion(editor) {
    if (!await this.checkAPI())
      return;
    const text = this.getSelectedText(editor);
    if (!text.trim()) {
      new import_obsidian3.Notice("\u8BF7\u5148\u9009\u4E2D\u8981\u54A8\u8BE2\u7684\u6587\u672C\uFF0C\u6216\u786E\u4FDD\u6587\u6863\u4E2D\u6709\u5185\u5BB9");
      return;
    }
    new import_obsidian3.Notice("\u6B63\u5728\u751F\u6210 AI \u89C2\u70B9...");
    this.setStatusBarLoading("\u751F\u6210\u4E2D...");
    try {
      const opinion = await this.deepSeekAPI.provideOpinion(text);
      this.clearStatusBarLoading();
      const endPos = editor.getCursor("to");
      editor.setCursor(endPos.line + 1, 0);
      editor.replaceSelection(`

## AI \u89C2\u70B9\u54A8\u8BE2

${opinion}

---
`);
      new import_obsidian3.Notice("\u2705 AI \u89C2\u70B9\u5DF2\u6DFB\u52A0\u5230\u6587\u6863");
    } catch (error) {
      this.clearStatusBarLoading();
      new import_obsidian3.Notice(`\u274C \u751F\u6210\u5931\u8D25: ${error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"}`);
      console.error("DeepSeek \u89C2\u70B9\u54A8\u8BE2\u9519\u8BEF:", error);
    }
  }
  async optimizeAndInsights(editor) {
    if (!await this.checkAPI())
      return;
    const text = this.getSelectedText(editor);
    if (!text.trim()) {
      new import_obsidian3.Notice("\u8BF7\u5148\u9009\u4E2D\u8981\u5904\u7406\u7684\u6587\u672C\uFF0C\u6216\u786E\u4FDD\u6587\u6863\u4E2D\u6709\u5185\u5BB9");
      return;
    }
    new import_obsidian3.Notice("\u6B63\u5728\u4F18\u5316\u6587\u672C\u5E76\u751F\u6210\u601D\u7EF4\u542F\u53D1...");
    this.setStatusBarLoading("\u5904\u7406\u4E2D...");
    try {
      const [optimized, insights] = await Promise.all([
        this.deepSeekAPI.optimizeText(text),
        this.deepSeekAPI.generateInsights(text)
      ]);
      this.clearStatusBarLoading();
      if (this.settings.autoReplace) {
        const selection = editor.getSelection();
        if (selection) {
          editor.replaceSelection(optimized);
        } else {
          editor.setValue(optimized);
        }
        const endPos = editor.getCursor("to");
        editor.setCursor(endPos.line + 1, 0);
        editor.replaceSelection(`

## \u601D\u7EF4\u542F\u53D1

${insights}

---
`);
      } else {
        const endPos = editor.getCursor("to");
        editor.setCursor(endPos.line + 1, 0);
        editor.replaceSelection(`

## \u4F18\u5316\u540E\u7684\u6587\u672C

${optimized}

## \u601D\u7EF4\u542F\u53D1

${insights}

---
`);
      }
      new import_obsidian3.Notice("\u2705 \u5904\u7406\u5B8C\u6210");
    } catch (error) {
      this.clearStatusBarLoading();
      new import_obsidian3.Notice(`\u274C \u5904\u7406\u5931\u8D25: ${error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"}`);
      console.error("DeepSeek \u7EC4\u5408\u529F\u80FD\u9519\u8BEF:", error);
    }
  }
  async optimizeAndOpinion(editor) {
    if (!await this.checkAPI())
      return;
    const text = this.getSelectedText(editor);
    if (!text.trim()) {
      new import_obsidian3.Notice("\u8BF7\u5148\u9009\u4E2D\u8981\u5904\u7406\u7684\u6587\u672C\uFF0C\u6216\u786E\u4FDD\u6587\u6863\u4E2D\u6709\u5185\u5BB9");
      return;
    }
    new import_obsidian3.Notice("\u6B63\u5728\u4F18\u5316\u6587\u672C\u5E76\u751F\u6210 AI \u89C2\u70B9...");
    this.setStatusBarLoading("\u5904\u7406\u4E2D...");
    try {
      const [optimized, opinion] = await Promise.all([
        this.deepSeekAPI.optimizeText(text),
        this.deepSeekAPI.provideOpinion(text)
      ]);
      this.clearStatusBarLoading();
      if (this.settings.autoReplace) {
        const selection = editor.getSelection();
        if (selection) {
          editor.replaceSelection(optimized);
        } else {
          editor.setValue(optimized);
        }
        const endPos = editor.getCursor("to");
        editor.setCursor(endPos.line + 1, 0);
        editor.replaceSelection(`

## AI \u89C2\u70B9\u54A8\u8BE2

${opinion}

---
`);
      } else {
        const endPos = editor.getCursor("to");
        editor.setCursor(endPos.line + 1, 0);
        editor.replaceSelection(`

## \u4F18\u5316\u540E\u7684\u6587\u672C

${optimized}

## AI \u89C2\u70B9\u54A8\u8BE2

${opinion}

---
`);
      }
      new import_obsidian3.Notice("\u2705 \u5904\u7406\u5B8C\u6210");
    } catch (error) {
      this.clearStatusBarLoading();
      new import_obsidian3.Notice(`\u274C \u5904\u7406\u5931\u8D25: ${error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"}`);
      console.error("DeepSeek \u7EC4\u5408\u529F\u80FD\u9519\u8BEF:", error);
    }
  }
  async allFeatures(editor) {
    if (!await this.checkAPI())
      return;
    const text = this.getSelectedText(editor);
    if (!text.trim()) {
      new import_obsidian3.Notice("\u8BF7\u5148\u9009\u4E2D\u8981\u5904\u7406\u7684\u6587\u672C\uFF0C\u6216\u786E\u4FDD\u6587\u6863\u4E2D\u6709\u5185\u5BB9");
      return;
    }
    new import_obsidian3.Notice("\u6B63\u5728\u6267\u884C\u5168\u90E8\u529F\u80FD...");
    this.setStatusBarLoading("\u5904\u7406\u4E2D...");
    try {
      const [optimized, insights, opinion] = await Promise.all([
        this.deepSeekAPI.optimizeText(text),
        this.deepSeekAPI.generateInsights(text),
        this.deepSeekAPI.provideOpinion(text)
      ]);
      this.clearStatusBarLoading();
      if (this.settings.autoReplace) {
        const selection = editor.getSelection();
        if (selection) {
          editor.replaceSelection(optimized);
        } else {
          editor.setValue(optimized);
        }
        const endPos = editor.getCursor("to");
        editor.setCursor(endPos.line + 1, 0);
        editor.replaceSelection(`

## \u601D\u7EF4\u542F\u53D1

${insights}

## AI \u89C2\u70B9\u54A8\u8BE2

${opinion}

---
`);
      } else {
        const endPos = editor.getCursor("to");
        editor.setCursor(endPos.line + 1, 0);
        editor.replaceSelection(`

## \u4F18\u5316\u540E\u7684\u6587\u672C

${optimized}

## \u601D\u7EF4\u542F\u53D1

${insights}

## AI \u89C2\u70B9\u54A8\u8BE2

${opinion}

---
`);
      }
      new import_obsidian3.Notice("\u2705 \u5168\u90E8\u529F\u80FD\u5904\u7406\u5B8C\u6210");
    } catch (error) {
      this.clearStatusBarLoading();
      new import_obsidian3.Notice(`\u274C \u5904\u7406\u5931\u8D25: ${error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"}`);
      console.error("DeepSeek \u5168\u90E8\u529F\u80FD\u9519\u8BEF:", error);
    }
  }
};
